blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/romkey/circremote/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/romkey/circremote#readme
    about: Check the README and documentation first. 