# SPDX-FileCopyrightText: 2025 John Romkey
#
# SPDX-License-Identifier: MIT

services:
  circremote:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: circremote
    image: circremote:latest
    volumes:
      - ~/.circremote:/home/circremote/.circremote:ro
      - .:/workspace:rw
      - /dev/bus/usb:/dev/bus/usb:ro
      - /dev/serial/by-id:/dev/serial/by-id:ro
      - ~/.cache/circup:/home/circremote/.cache/circup:rw
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: host
    restart: unless-stopped
    command: ["--help"]

  # Alternative service for running specific circremote commands
  circremote-run:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: circremote-run
    image: circremote:latest
    volumes:
      - ~/.circremote:/home/circremote/.circremote:ro
      - .:/workspace:rw
      - /dev/bus/usb:/dev/bus/usb:ro
      - /dev/serial/by-id:/dev/serial/by-id:ro
      - ~/.cache/circup:/home/circremote/.cache/circup:rw
    working_dir: /workspace
    network_mode: host
    # This service is meant to be run with specific commands
    # Example: docker-compose run circremote-run /dev/ttyUSB0 BME280
    profiles:
      - run 