name: PR Notification

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  notify-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Notify @romkey of new PR
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const pr = context.payload.pull_request;
            
            // Create a comment to notify the repo owner
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: `🔔 **New Pull Request Notification**
              
              @${owner}, a new pull request has been submitted:
              
              **PR #${number}**: ${pr.title}
              **Author**: @${pr.user.login}
              **Branch**: \`${pr.head.ref}\` → \`${pr.base.ref}\`
              **Created**: ${new Date(pr.created_at).toLocaleString()}
              
              ${pr.body ? `**Description**:\n${pr.body.substring(0, 200)}${pr.body.length > 200 ? '...' : ''}` : '**No description provided**'}
              
              [View Pull Request](https://github.com/${owner}/${repo}/pull/${number})
              
              ---
              *This notification was automatically generated by GitHub Actions*`
            });
            
            // Add the repo owner as assignee if not already assigned
            const currentAssignees = pr.assignees.map(a => a.login);
            if (!currentAssignees.includes(owner)) {
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: number,
                assignees: [owner]
              });
            }
            
            console.log(`✅ Notified @${owner} about PR #${number}`); 